# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: macos-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '23.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'android'  # Adjusted path if gradlew is in the root directory
    workingDirectory: 'src/android'  # Ensure this is the correct directory
    options: '-Xmx3072m'
    tasks: 'assembleRelease'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false


- task: PublishBuildArtifacts@1
  displayName: 'Publish APK to artifacts'
  inputs:
    PathtoPublish: 'android/app/build/outputs/apk/release'
    ArtifactName: 'android'
    publishLocation: 'Container'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/'
    azureSubscription: 'subscription'  # Replace with your Azure subscription service connection
    Destination: 'AzureBlob'
    storage: '$(STORAGE_ACCOUNT)'  # Replace with your Azure Storage account name
    ContainerName: '$(CONTAINER_NAME)'  # Replace with the Azure Blob container name
    BlobPrefix: 'react-native-builds/'  # Prefix to categorize builds
  displayName: 'Upload APK and App Bundle to Azure Blob Storage'
