trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  ANDROID_KEYSTORE_PASSWORD: $(ANDROID_KEYSTORE_PASSWORD)
  ANDROID_KEY_PASSWORD: $(ANDROID_KEY_PASSWORD)
  ANDROID_KEYSTORE_ALIAS: $(ANDROID_KEYSTORE_ALIAS)
  ANDROID_KEY_ALIAS: $(ANDROID_KEY_ALIAS)
  ANDROID_KEYSTORE_PATH: '$(Build.SourcesDirectory)/android/app/my-release-key.keystore'
  AZURE_SUBSCRIPTION: $(AZURE_SUBSCRIPTION)
  STORAGE_ACCOUNT: $(STORAGE_ACCOUNT)
  CONTAINER_NAME: $(CONTAINER_NAME)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g react-native-cli
  displayName: 'Install React Native CLI'

- script: |
    export JAVA_HOME=$(/usr/libexec/java_home -v 17)
    echo "JAVA_HOME is set to $JAVA_HOME"
    cd android
    ./gradlew clean
    ./gradlew assembleRelease --warning-mode all
  displayName: 'Build Release APK and App Bundle with Warnings'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/'
    azureSubscription: subscription
    Destination: 'AzureBlob'
    storage: $(STORAGE_ACCOUNT)
    ContainerName: $(CONTAINER_NAME)
    BlobPrefix: 'react-native-builds/'
  displayName: 'Upload APK and App Bundle to Azure Blob Storage'
