trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

variables:
  KEYSTORE_PATH: $(Pipeline.Workspace)/keystore.keystore

steps:
  # Download the keystore from Secure Files
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'my-release-key.keystore'

  # Build the app using the secure passwords
  - script: |
      npm install
      cd android
      ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=$(KEYSTORE_PATH) \
        -Pandroid.injected.signing.store.password=$(KEYSTORE_PASSWORD) \
        -Pandroid.injected.signing.key.alias=$(KEY_ALIAS) \
        -Pandroid.injected.signing.key.password=$(KEY_PASSWORD)
    displayName: 'Build APK and App Bundle'

  # Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/'
      artifactName: 'AppArtifacts'

  # Upload APK and App Bundle to Azure Storage
  - task: AzureFileCopy@4
    inputs:
      SourcePath: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/'
      azureSubscription: $(AZURE_SUBSCRIPTION)
      Destination: 'AzureBlob'
      storage: $(STORAGE_ACCOUNT)
      ContainerName: $(CONTAINER_NAME)
      BlobPrefix: 'react-native-builds/'
