trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'

variables:
  # Keystore and password variables
  KEYSTORE_PATH: $(Build.SourcesDirectory)/keystore.keystore
  KEYSTORE_PASSWORD: $(KEYSTORE_PASSWORD)  # Make sure this is set as a secret variable
  KEY_ALIAS: $(KEY_ALIAS)  # Make sure this is set as a secret variable
  KEY_PASSWORD: $(KEY_PASSWORD)  # Make sure this is set as a secret variable

steps:
  # Checkout the code from the repo
  - checkout: self

  # Install dependencies
  - script: |
      npm install
    displayName: 'Install Dependencies'

  # Build APK and App Bundle (AAB) with signing information
  - script: |
      cd android
      ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=$(KEYSTORE_PATH) \
        -Pandroid.injected.signing.store.password=$(KEYSTORE_PASSWORD) \
        -Pandroid.injected.signing.key.alias=$(KEY_ALIAS) \
        -Pandroid.injected.signing.key.password=$(KEY_PASSWORD)
    displayName: 'Build APK and App Bundle'
    
  # Publish artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/'
      artifactName: 'AppArtifacts'

  # Upload APK and App Bundle to Azure Storage
  - task: AzureFileCopy@4
    inputs:
      SourcePath: '$(System.DefaultWorkingDirectory)/android/app/build/outputs/'
      azureSubscription: $(AZURE_SUBSCRIPTION)
      Destination: 'AzureBlob'
      storage: $(STORAGE_ACCOUNT)
      ContainerName: $(CONTAINER_NAME)
      BlobPrefix: 'react-native-builds/'
